### ISSUE TITLE
accelerate-cuda does not compile with cuda-0.7.0.0

### ISSUE THREAD

**Issue by MKloczko** [MKloczko/accelerate-cuda#2]
As the title says. 
```
Data/Array/Accelerate/CUDA/Context.hs:68:43:
    Not in scope: ‘CUDA.setCacheConfig’
    Perhaps you meant ‘CUDA.setCacheConfigFun’ (imported from Foreign.CUDA.Driver)

Data/Array/Accelerate/CUDA/Context.hs:155:57:
    Not in scope: ‘CUDA.useDevice’
    Perhaps you meant one of these:
      ‘CUDA.useDevicePtr’ (imported from Foreign.CUDA.Driver),
      ‘CUDA.device’ (imported from Foreign.CUDA.Driver.Context)
```

**Comment by MKloczko** [comment]
Fixed.
